<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Refit" Version="12.0.0" />
      <PackageReference Include="Refit.HttpClientFactory" Version="12.0.0" />
      <PackageReference Include="Refit.Newtonsoft.Json" Version="12.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="Components\Layout\MainLayout.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Layout\ReconnectModal.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Layout\NavBar.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Layout\Footer.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Home.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\NotFound.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Dialog.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Instrutores.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Modalidades.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Aulas.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Login.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddSocio.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddAula.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\TipoPlano.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Salas.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddTipoPlano.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddInstrutor.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddModalidade.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddSala.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddUser.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Inscricoes.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\NivelDificuldade.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddInscricao.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Users.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddNivelDificuldade.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AddInstrutorModalidade.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\InstrutorModalidade.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Dashboard.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\PaginaListar.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\AulaDetail.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\Socios.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Pages\SocioDetail.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Components\Layout\PaginaListar.razor">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
    </ItemGroup>

</Project>
